### ISSUE TITLE
Vaadin 8 Incompatible.

### ISSUE THREAD

**Issue by phenry01** [pleku/resizablecsslayout#14]
Hi,

While the code itself is compatible with Vaadin 8 there are some issues with the compiled code in release 1.1.0 when used with Vaadin 8.

If you extend ResizableCssLayoutState then you get a StackOverFlowError whenever you call getState(boolean) ... which is called indirectly in the constructor of ResizableCSSLayout.

Recompiling the addon against Vaadin 8 resolves this issue and allows you to extend ResizableCssLayout

This may be related to bridge methods created in the compiled class file for ResizableCssLayout. In Vaadin 7 CssLayout did not define a getState(boolean) method, so when ResizableCssLayout is compiled against the Vaadin 7 code base the compiled class file adds bridge methods because ResizableCssLayout overrides the return type of getState(boolean) casting the returned state to a  ResizableCssLayoutState.

**Comment by taurus227** [comment]
Created a pull request, which solves the StackOverFlowError issue.

**Comment by pleku** [comment]
Fixed via #15
